### ISSUE TITLE
publishtspec is unclear now

### ISSUE THREAD

**Issue by zxcat** [GolosChain/golos.worker#11]
Current implementation contains `publishtspec` & `startwork` actions. The problem is `publishtspec` somewhat unclear, it can be called several times or don't called at all, because it doesn't change the state of proposal.

Form clearer conditions for `publishtspec` and `startwork`.

**Comment by afalaleev** [comment]
I don't see differences between edittspec  and publishtspec.
Publishtspec can be deleted.

**Comment by denis4net** [comment]
Removed in #16
