### ISSUE TITLE
Update voting module

### ISSUE THREAD

**Issue by zxcat** [GolosChain/golos.worker#3]
- [x] 1. Is `count()` work correct if no votes exists? Fix if invalid (or remove if not used):
https://github.com/GolosChain/golos.worker/blob/d47729cbe0c2a77e9c6c343a96af65c1c471f066/contracts/golos.worker/golos.worker.cpp#L144
- [x] 2. `vote()` must disallow casting same vote, add `eosio_assert(false, …)` to `else` branch: https://github.com/GolosChain/golos.worker/blob/d47729cbe0c2a77e9c6c343a96af65c1c471f066/contracts/golos.worker/golos.worker.cpp#L151-L156
- [x] 3. Add test, that checks votes module:
    + no vote exists at initial state
    + vote added after `vote()`
    + assert on 2nd `vote()` with same `.positive` value
    + success on `vote()` with different `.positive` value
    + if would be good to test other module functions too, but looks like it's not very easy, so optional and lowest priority

**Comment by denis4net** [comment]
Fixes in #13
