### ISSUE TITLE
Improve tests of comment module

### ISSUE THREAD

**Issue by zxcat** [GolosChain/golos.worker#4]
`comment_CUD` test case contains base checks of comment module, we need to cover fails too:

- [x] add test to ensure fail when adding comment with same id
- [x] add test to ensure fail when deleting non-existing comment
- [x] add test to ensure fail when editing comment with empty text
- [x] add test to ensure fail when editing non-existing comment
- [x] add test to check `get_proposal_comments_count` value is equal to `comments_count` after creating/editing comments
- [x] add test to check `get_proposal_comments_count` value is equal to 0 after deleting comments

**Comment by denis4net** [comment]
Fixed in #14
