### ISSUE TITLE
Remove app_domain

### ISSUE THREAD

**Issue by zxcat** [GolosChain/golos.worker#5]
Earlier it's planned to have one workers smart-contract connected to several communities, and app_domain required to detect, which community uses contract. This makes workers smart-contract system-like, so all communities forced to use same code base.
Now we move to more flexible community structure, where code of each smart-contract can be changed to fit community needs, so individual workers smart-contract instances (possibly, modified) deployed by communities, which need this smart-contract.

`app_domain` functionality is no more needed, we can remove it to make smart-contract simpler.

- [ ] update constructor to work without `app` argument
- [ ] change `_app` to `_self`, where possible (e.g. `require_auth`)
- [ ] remove `APP_DOMAIN_ABI`
- [ ] looks like `process-abi.py` can be removed too
- [ ] `scope` of tables is now free to use, so table access can be simplified (maybe remove secondary index and use `scope` instead). optional, low priority

**Comment by denis4net** [comment]
Fixed in #15
