### ISSUE TITLE
Minor fixes

### ISSUE THREAD

**Issue by zxcat** [GolosChain/golos.worker#6]
Moved minor (mostly 1-line) issues and bugs from #1 review:

- [x] Use `get_funds` instead of: https://github.com/GolosChain/golos.worker/blob/d47729cbe0c2a77e9c6c343a96af65c1c471f066/contracts/golos.worker/golos.worker.cpp#L359-L360
- [x] There is no need to pass `modifier` here, because stored data size can't grow on updating that record, use `name()` instead: https://github.com/GolosChain/golos.worker/blob/d47729cbe0c2a77e9c6c343a96af65c1c471f066/contracts/golos.worker/golos.worker.cpp#L365
- [x] Community upvotes don't prevent proposal deletion, remove this assert: https://github.com/GolosChain/golos.worker/blob/d47729cbe0c2a77e9c6c343a96af65c1c471f066/contracts/golos.worker/golos.worker.cpp#L605 (approvements will be described with more details in separate issue)
- [x] Please rename `author` to `voter`: https://github.com/GolosChain/golos.worker/blob/d47729cbe0c2a77e9c6c343a96af65c1c471f066/contracts/golos.worker/golos.worker.cpp#L631
- [x] Add check of `quantity` symbol in `setfund` action: https://github.com/GolosChain/golos.worker/blob/d47729cbe0c2a77e9c6c343a96af65c1c471f066/contracts/golos.worker/golos.worker.cpp#L550
- [x] `uint8_t` is too small for `payments_count`. it's not enough to cover year if pay once per day. let change it to `uint16_t`:  https://github.com/GolosChain/golos.worker/blob/d47729cbe0c2a77e9c6c343a96af65c1c471f066/contracts/golos.worker/golos.worker.cpp#L183

**Comment by denis4net** [comment]
> * [ ]  Community upvotes don't prevent proposal deletion, remove this assert: 
>     
>       
>         [golos.worker/contracts/golos.worker/golos.worker.cpp](https://github.com/GolosChain/golos.worker/blob/d47729cbe0c2a77e9c6c343a96af65c1c471f066/contracts/golos.worker/golos.worker.cpp#L605)
>       
>       
>            Line 605
>         in
>         [d47729c](/GolosChain/golos.worker/commit/d47729cbe0c2a77e9c6c343a96af65c1c471f066)
>       
>       

Look at SRS 1.E `Автор может удалить свое предложение на добавление функционала, если это предложение еще не получило ни одного одобрения делегатом.`

**Comment by zxcat** [comment]
> Look at SRS 1.E Автор может удалить свое предложение на добавление функционала, если это предложение еще не получило ни одного одобрения делегатом.

`votepropos` доступен всем, а не только делегатам:
https://github.com/GolosChain/golos.worker/blob/d47729cbe0c2a77e9c6c343a96af65c1c471f066/contracts/golos.worker/golos.worker.cpp#L631-L636

а во-вторых, это как «лайк», а не одобрение. то есть это разные вещи: члены сообщества ставят апвоуты/даунвоуты, это просто чтоб увидеть какой-то условный рейтинг. делегаты же могу одобрить (approve) заявку на тз, это другая механика. и предложение, у которого есть заявки с одобрениями не могут быть удалены
> (1.c: Голосование делегатов за предложение происходит через голосование по заявкам на составление технического задания)

**Comment by denis4net** [comment]
@zxcat, got it. I was confused by the statetment.

**Comment by denis4net** [comment]
@zxcat, got it

**Comment by denis4net** [comment]
@zxcat is this right implementation https://github.com/GolosChain/golos.worker/pull/13/commits/e6b9901418347f90d5d338f20a750b34ca848af6?

**Comment by denis4net** [comment]
Fixed in #13
